### ISSUE TITLE
New document ID not unique after fork

### ISSUE THREAD

**Issue by jdsutton7** [googleapis/python-firestore#346] opened 2021-04-30 19:09 UTC
Originally reported here: https://github.com/firebase/firebase-admin-python/issues/548

If firebase_admin is imported before os.fork(), auto-generated document IDs are repeated causing data to be overwritten.

#### Environment details

  - OS type and version: Linux Mint 20
  - Python version: Python 3.6.13
  - pip version: pip 21.1
  - `google-cloud-firestore` version: 2.1.0

#### Steps to reproduce

Import firebase_admin, fork, create firestore client, write a new document.

#### Code example

```python
#!/usr/bin/env python3.6

import os
import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore

pid = os.fork()

cred = credentials.Certificate('service_account.json')
firebase_admin.initialize_app(cred)

client = firestore.client()

if pid == 0:
    reference = client.collection('Test').document()
    reference.set({'a': 'b'})

    print('Child: ' + reference.id)
else:
    reference = client.collection('Test').document()
    reference.set({'a': 'c'})

    print('Parent: ' + reference.id)
```
Output:
```
Child: TCsit2S0VQgvqm0aHNTc
Parent: TCsit2S0VQgvqm0aHNTc
```

**Comment by crwilcox** [comment] 2021-04-30 21:32
This is the function that generates auto id. https://github.com/googleapis/python-firestore/blob/1d5c19a350bfb2337a3e3dfe520b1a464519433c/google/cloud/firestore_v1/base_collection.py#L451

The seed is determined at import time. To get unique seeds, I think auto_id needs to explicitly call `seed`. This could be done once per fork, but it may be inexpensive enough to just do this each and every time an `_auto_id` is needed.

```
random.seed()
```

**Comment by crwilcox** [comment] 2021-05-04 22:29
Followup: I think for Go, possibly other clients, we do not set an id at all. This allows the server to choose the id, and the returned result contains the id as selected.

**Comment by Sylphias** [comment] 2021-06-28 09:42
I'm also currently facing this issue. Firestore is constantly generating the same auto_id regardless of how many times I re-initialize my firebase client in my app.

The temporary workaround that I've tested is to run `random.seed()` (as @crwilcox has mentioned above) before .add() is called. This generates the auto_id properly.

I'm running this with a streamlit application and I hypothesize that it runs os.fork before my code is run.

**Comment by jdsutton7** [comment] 2021-07-01 00:20
This issue should arguably be a higher priority as it can result in
production data being silently overwritten.

Another quick temporary fix is to provide your own IDs with uuid.uuid4()

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by crwilcox** [comment] 2021-07-02 23:04
In an effort to keep the randomly generated names in line with what the backend will do, I have modified the auto_id method to reseed each run. The performance penalty should be minimal and collisions shouldn't happen.

The better solution would be to rework the client to not try and manage auto id at all, allowing firestore to decide at request time, but in looking into this it seems this would be more involved. I have created a tracking issue for that, but this fix should avoid the issue with forked clients.

**Comment by crwilcox** [comment] 2021-07-03 05:16
Thanks for the update @jdsutton7 . I have looked into this and it seems to be a narrower repro than presented.  In short 3.7+ is fine and this appears to be an issue with 3.6 versions of Python specifically.

On Ubuntu 20, I have used CPython versions

- 3.9.6
- 3.8.11
- 3.7.11
- 3.6.12 -> repros
- 3.6.14 -> repros

The repro, provided by @jdsutton7 in a linked bug.

```
import os

from google.cloud import firestore

pid = os.fork()

client = firestore.Client()

if pid == 0:
    reference = client.collection('Test').document()
    print('Child:', reference.id)
else:
    reference = client.collection('Test').document()
    print('Parent:', reference.id)
```

**Comment by stphnthiel** [comment] 2022-05-19 08:10
I am still seeing that same effect on python `3.8.10` on `Ubuntu 20.04.3 LTS` (NVIDIA Docker image), but it is **very** hard to reproduce.

This also explains my somewhat big frustration with this issue, as it has been silently overwriting production data in a current project. What is especially hard is that the Firestore documentation [treats these two ways to add data the same](https://firebase.google.com/docs/firestore/manage-data/add-data#add_a_document):

1.

```python
city = City(name=u'Tokyo', state=None, country=u'Japan')
db.collection(u'cities').add(city.to_dict())
```

2.

```python
new_city_ref = db.collection(u'cities').document()

# later...
new_city_ref.set({
    # ...
})
```

However, if you use approach no. 2 and run into this issue with existing IDs being returned by `.document()` you **will** overwrite existing data without any warning! The `.add()` approach at least throws a document exists.

I can’t emphasize enough that this should be addressed with the highest priority IMHO.

Further going to the bottom of this, I am very much interested in why such a peculiar approach to generating IDs was chosen in the first place? All of this frustration could be easily avoided by choosing established methods to generating truly unique IDs in Firestore per default, e.g. UUID4.

My current approach is to call `random.seed()` before any adding any data...

**Comment by crwilcox** [comment] 2022-05-19 23:22
Hi @stphnthiel, I've since moved to a different project, but someone should be able to pick this up. The original issue was highly reproducible. My guess is the root cause was accurate, that the seed randomization on fork is addressed. There may be something else at play here for you though. When you say 'hard to reproduce' how often are you having collisions?  

For background, the reason this approach was historically used is it mimics the type of ID you would receive from the cloud console. Other clients do similar things. Without this, you would get IDs of different styles based on which client or UI created a document.

One alternative considered was to not set an id at all on the client side. The API, if I recall correctly, will accept a set document without an ID, see it as a new document, and return the ID that it was created as. There were I think some reasons this wouldn't work well in the client, but I can't be sure.

Another alternative, looking at this code again, would be to use `os.urandom` instead of `random.choice`.

**Comment by stphnthiel** [comment] 2022-05-20 07:37
Hi @crwilcox thanks to getting back so quickly!

I would have to do thorough testing to tell. About 10% of calls to `.document()` would return an existing ID. My setup is as follows:

* FastAPI dev server using the Firebase lib or production server based on `uvicorn` (one worker)
* parallel to that I am using an iPython session with `auto_reload` to create data
* All of this inside a Docker container (Ubuntu `20.04`, Python `3.8`)

So it’s hard to tell where there might be duplicate instances running. I’ll try to narrow this down with more info.

Totally understand the history on the IDs and why it’s harder to change this. I guess it would have to be tackled on a higher level.

**Comment by jdsutton7** [comment] 2022-05-20 15:37
Your issue is most likely related to the statefulness of iPython imo, since
you are seeing this in Python3.8

Are you able to reproduce the issue in 3.8 using simple forking without
iPython etc?

**Comment by jdsutton7** [comment] 2022-05-23 15:32
It sounds like your issue is not coming from firestore, then. For the short
term you can generate your own IDs with uuid4, and follow up on the issue
at it's source if desired.

**Comment by Mariatta** [comment] 2023-02-17 21:11
It doesn't seem like this is an actual bug with the client library but with the Python environment. So I'm closing this. Thanks.

**Closed by Mariatta** 2023-02-17 21:11 UTC
Labels: api: firestore, type: bug, priority: p2, :rotating_light:

**Comment by nikcaryo-super** [comment] 2024-09-09 15:55
Also just ran into this. I agree with @stphnthiel. Documentation should be updated. `.add()` seems to throw an exception if it's going to replace an existing document. `document()` does not. So the two are not equivalent and the documentation should suggest checking to see if the id returned by `.document` already exists.
