### ISSUE TITLE
grpc._channel._MultiThreadedRendezvous fails; StatusCode.UNAVAILABLE; Query timed out

### ISSUE THREAD

**Issue by brent-ridian** [googleapis/python-firestore#939] opened 2024-07-18 19:18 UTC
#### Environment details

  - OS type and version: I use Windows locally, and Linux in prd
  - Python version: I use the latest release of Python, which is currently Python 3.12.4
  - pip version: pip 24.1.2
  - `google-cloud-firestore` version: 2.16.1

My guess is that the bug I report below is independent of OS, Python version, pip version but very well may depend on firestore version.

#### Steps to reproduce

 Non trivial.  As described in "The Bug" section below, the bug only manifests when I try to read every document in my company's **biggest** collection.  _All our other collections do not trigger the bug_.  If someone from Google reaches out to me, I would be glad to share precise details of that collection.

#### Code example

Included in "The Bug" section below

#### Stack trace

Included in "The Bug" section below

#### The Bug

I am seeing the exact same issue as was reported in [this StackOverflow link](https://stackoverflow.com/questions/78605344/how-to-fix-grpc-channel-multithreadedrendezvous-fails-statuscode-unavailable).

The Google engineer [dconeybe in this link](https://github.com/googleapis/nodejs-firestore/issues/2055) recommended that I file a bug report in this GitHub project, since he suspects that the bug is in the Firestore Python client library.

So, the text below is my adaptation of that StackOverflow:

I have a Python function that takes a cloud Firestore collection name as an arg and streams thru every document in that collection to check for errors.

In simplified form, it essentially looks something like this:

```
from firebase_admin import firestore

def find_all_issues(collection: str) -> None:
    fs_client = firestore.client()
    coll_ref = fs_client.collection(collection)
    doc_snapshot_stream = coll_ref.stream()
    for doc_snap in doc_snapshot_stream:
        d = doc_snap.to_dict()
        # perform error checks on d
```

The key point here is that I create a stream for the collection and use that to read and process **every** document in the collection.

_The code always works perfect on all but one of my collections._

Unfortunately, on the **biggest** collection, I not infrequently get an error like this:

```
Traceback (most recent call last):
  File "...\virtualenvs\backend-venv\Lib\site-packages\google\api_core\grpc_helpers.py", line 116, in __next__
    return next(self._wrapped)
           ^^^^^^^^^^^^^^^^^^^
  File "...\virtualenvs\backend-venv\Lib\site-packages\grpc\_channel.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "...\virtualenvs\backend-venv\Lib\site-packages\grpc\_channel.py", line 969, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Query timed out. Please try either limiting the entities scanned, or run with an updated index configuration."
	debug_error_string = "UNKNOWN:Error received from peer ipv4:142.250.9.95:443 {created_time:"2024-07-18T15:21:04.3215985+00:00", grpc_status:14, grpc_message:"Query timed out. Please try either limiting the entities scanned, or run with an updated index configuration."}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "...\virtualenvs\backend-venv\Lib\site-packages\google\cloud\firestore_v1\query.py", line 361, in stream
    response = next(response_iterator, None)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\virtualenvs\backend-venv\Lib\site-packages\google\api_core\grpc_helpers.py", line 119, in __next__
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ServiceUnavailable: 503 Query timed out. Please try either limiting the entities scanned, or run with an updated index configuration.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...\firestore_data_investigation.py", line 258, in <module>
    check_collections(stop_if_issue = False)
  File "...\firestore_data_investigation.py", line 133, in check_collections
    num_docs, issues = all_issues(XXX.COLLECTION)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\XXX_integration_test.py", line 390, in all_issues
    for doc_snap in doc_snapshots:
  File "...\virtualenvs\backend-venv\Lib\site-packages\google\cloud\firestore_v1\query.py", line 363, in stream
    if self._retry_query_after_exception(exc, retry, transaction):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\virtualenvs\backend-venv\Lib\site-packages\google\cloud\firestore_v1\query.py", line 240, in _retry_query_after_exception
    retry = gapic_callable._retry
            ^^^^^^^^^^^^^^^^^^^^^
AttributeError: '_UnaryStreamMultiCallable' object has no attribute '_retry'
```

This is super frustrating. _I can't believe that Firestore cannot create and maintain a rock solid database stream!_

The error message offers this very useful sounding advice: `Please try either limiting the entities scanned, or run with an updated index configuration.`

The problem is that I have no idea how to execute on it:

1. `limiting the entities scanned`: how can I possibly do that? I need to process every document in the collection! Furthermore, I really hope that Google is not expecting Firestore users to somehow manually break up large reads.
2. `run with an updated index:` **I have no idea what index to use to solve this problem**. In other Firestore contexts, I have seen Google's error message very helpfully give you the exact index command you should execute to solve the problem. Unfortunately, here Google tells me nothing.

**Comment by Linchin** [comment] 2024-07-19 19:45
Assigning to @daniel-sanche who has more knowledge about the Firestore SDK.

A possible clue from a quick google search: [this stackoverflow thread](https://stackoverflow.com/questions/74401056/what-is-an-updated-index-configuration-of-google-firestore-in-datastore-mode) suggests this may be caused by a large number of docs that are still being updated. I wonder if this has any similarity to your case.

**Comment by brent-ridian** [comment] 2024-07-19 20:05
Linchin: thx for the update.

My guess is that your SO thread does not apply to me: I only see the error reported here when I am trying to read every document in my largest collection, and the vast majority of the documents in that collection are not being updated.  At most, maybe about 200 theoretically could be, but in practice, I bet that many fewer than that are.

**Comment by brent-ridian** [comment] 2024-07-26 16:10
Google: are you here?

**Comment by ozayr** [comment] 2024-08-22 05:56
had the same issue, this worked for me 

```
def update_collection_paginated(page_size=20000):
    query = db_prod.collection('someCollection').where(filter=SomeFilter)
    
    # Get the first page
    docs = query.limit(page_size).stream()
    
    batches = [db_prod.batch()]
    current_batch = 0
    operation_count = 0
    
    last_doc = None
    
    while True:
        doc_count = 0
        for doc in tqdm(docs, total=page_size):
            doc_count += 1
            last_doc = doc
            
            doc_dict = doc.to_dict()
            try:
                # some update logic here
                
            except KeyError:
                pass
            
            batches[current_batch].set(doc.reference, doc_dict)
            operation_count += 1
            
            # If the operation count reaches 500, move to the next batch
            if operation_count == 500:
                operation_count = 0
                current_batch += 1
                batches.append(db_prod.batch())
        
        # If we've processed fewer documents than the page size, we're done
        if doc_count < page_size:
            break
        
        # Construct a new query starting after the last document
        docs = query.start_after(last_doc).limit(page_size).stream()
    
    return batches

# Execute the paginated update
batches = update_visits_paginated()
for batch in tqdm(batches):
    batch.commit()
```

**Comment by brent-ridian** [comment] 2024-10-24 02:35
First, something that does NOT work:

The CollectionReference's stream method has a timeout arg,

I just tried running my code with it set to a really big value: timeout = 1e10.

Unfortunately, that choice does does not allow my code to work, it just changes the stacktrace to:

```
Traceback (most recent call last):
  File "...\backend-venv\Lib\site-packages\google\api_core\grpc_helpers.py", line 170, in error_remapped_callable
    return _StreamingResponseIterator(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\backend-venv\Lib\site-packages\google\api_core\grpc_helpers.py", line 92, in __init__
    self._stored_first_result = next(self._wrapped)
                                ^^^^^^^^^^^^^^^^^^^
  File "...\backend-venv\Lib\site-packages\grpc\_channel.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "...\backend-venv\Lib\site-packages\grpc\_channel.py", line 952, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "DEADLINE_EXCEEDED:Deadline Exceeded {grpc_status:4}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "...\backend-venv\Lib\site-packages\google\api_core\retry\retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "...\backend-venv\Lib\site-packages\google\api_core\timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "...\backend-venv\Lib\site-packages\google\api_core\grpc_helpers.py", line 174, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.DeadlineExceeded: 504 Deadline Exceeded
```

**Comment by brent-ridian** [comment] 2024-10-24 02:43
And now, the moment that you have been waiting for: something that does work:

Define this custom `Retry` instance:

```
from google.api_core import exceptions as core_exceptions
from google.api_core import retry as retries

custom_retry = retries.Retry(
	initial = 0.1,  # seconds
	maximum = 10_000.0,  # seconds
	multiplier = 1.3,
	predicate = retries.if_exception_type(
		core_exceptions.DeadlineExceeded,
		core_exceptions.ServiceUnavailable,
	),
	timeout = 10_000.0,  # seconds
)
```

Supply that in the call to stream as `coll_ref.stream(retry = custom_retry)`

_For me, that allowed my code to work: I can now iterate thru every document in my big collection._

Altho, I am not exactly sure why it works.  I just guessed at the maximum and timeout values to use in that Retry instance above.

I got inspired to try this when I stumbled across [Google's class OperationsClient](https://github.com/googleapis/python-api-core/blob/main/google/api_core/operations_v1/operations_client.py): its `__init__` defines a `default_retry` local var that I modified.

**Comment by daniel-sanche** [comment] 2024-10-24 18:11
Sorry for the late response! Yeah, in general when having issues with large queries, it can be helpful to adjust.

For reference, [this is the default Retry object](https://github.com/googleapis/python-firestore/blob/3fe727102d1a4f65c9b8767d11015d8baaead355/google/cloud/firestore_v1/services/firestore/transports/base.py#L274) that's applied when one isn't passed in (deadline is an alias for timeout)

```
retries.Retry(
    initial=0.1,
    maximum=60.0,
    multiplier=1.3,
    predicate=retries.if_exception_type(
        core_exceptions.DeadlineExceeded,
        core_exceptions.InternalServerError,
        core_exceptions.ResourceExhausted,
        core_exceptions.ServiceUnavailable,
    ),
    timeout=300.0,
),
```

It's likely your change to the timeout field in the retry that helped

---

Adjusting `coll_ref.stream(timeout=timeout)` should set the per-request timeout, where it will cancel the individual request if it takes longer than that timeframe (but possibly retry it). Setting `coll_ref.stream(retry=Retry(timeout=timeout))` sets the time after which the operation won't be retried, but does **not** cancel in-progress requests.

 
I'm not exactly sure why you're seeing a new error in https://github.com/googleapis/python-firestore/issues/939#issuecomment-2434112963 after giving it such a large timeout, but I'm glad you got it working

**Closed by daniel-sanche** 2024-10-24 18:11 UTC
Labels: api: firestore

**Comment by ahdkhalid** [comment] 2025-07-01 16:54
A working alternative solution is to iterate until before the timeout happens and reset stream function and start from where it left off.
Solution below, does the batched iteration, not overwhelming the stream function. Copied from [here](https://stackoverflow.com/a/56849656)

```
def collection_batched_iterate(collection_name, batch_size=300, cursor=None):
    query = client.collection(collection_name).limit(batch_size).order_by('__name__')
    if cursor:
        query = query.start_after(cursor)

    for doc in query.stream():
        yield doc
    
    if 'doc' in locals():
        yield from collection_batched_iterate(collection_name, batch_size, doc)
```
then, loop over the above iterator function:

```
for subscription in collection_batched_iterate("subscriptions"):
    # do your operations
```
