### ISSUE TITLE
Firestore: Async callbacks on_snapshot

### ISSUE THREAD

**Issue by mr-bjerre** [googleapis/python-firestore#3] opened 2020-01-28 17:39 UTC
**Problem**

I am writing a bunch of python applications that listens to news on firestore using `on_snapshot`. Some of the callbacks have IO-bound tasks which blocks other callbacks and builds up a queue.

Here's a mockup demonstrating the issue

```python
from google.cloud.firestore import Client
import time

def callback(col_snapshot, changes, read_time):
    print("Received updates")

    # mock IO-bound task
    time.sleep(1)
    print("Finished handling the updates")

Client().collection('news').on_snapshot(callback)

while True:
    pass
```

 **Solution**

I'm no expert on this matter but I'm guessing that `async` is the right path. It would be great if something like this would be possible

```python
from google.cloud.firestore import Client
import asyncio

async def callback(col_snapshot, changes, read_time):
    print("Received updates")

    # mock IO-bound task
    await asyncio.sleep(1)
    print("Finished handling the updates")

Client().collection('news').on_snapshot(callback)

while True:
    pass
```

 ** Alternatives **

I've also considered using `multithreading` but I think `async` is much preferred.

**Comment by MaticConradi** [comment] 2020-05-10 17:01
I'm looking forward to this. I'm using multiple snapshot listeners in my project where basically all operations are asynchronous. Not sure if this is related or not, but Firestore fails to call (seemingly random) listeners from time to time.

**Comment by therefromhere** [comment] 2020-06-12 04:01
With [google-api-core](https://googleapis.dev/python/google-api-core/latest/changelog.html) beginning to add AsyncIO support since version 1.18.0 it'd be awesome to get async support for firestore.

**Comment by mr-bjerre** [comment] 2020-12-01 09:38
Any updates on this? I've noted that you've added some `async` and `await` code in v2 but I can't find anything about in the docs?

**Comment by crwilcox** [comment] 2020-12-01 17:04
@mr-bjerre we did add a good amount of async surface to this client, though I don't believe we have made any changes to watch specifically. `async_client`, `async_batch`, `async_collection`, etc. Alongside their sync counter parts `client`, `batch`, `async_collection`, etc. 

We had made https://github.com/googleapis/python-firestore/issues/131 to track adding async watch support.

**Comment by craiglabenz** [comment] 2021-04-20 20:15
Closing this as a duplicate of #131 (even though this came first).

**Closed by craiglabenz** 2021-04-20 20:15 UTC
Labels: api: firestore, type: feature request
