### ISSUE TITLE
Encoding a nested object throws an error in the _helpers module in the encode_value function 

### ISSUE THREAD

**Issue by anantasty** [googleapis/python-firestore#386] opened 2021-06-30 12:52 UTC
#### Steps to reproduce

  1. Try to store a Dictonary containing a nested dictonary 
  2. ?

#### Code example

```python
nested = {"name": {"first": "John", "last": "Doe"}}
db.document("people/john").set(nested)
```

#### Stack trace
```
 File "/workspace/util.py", line 153, in host_external_check
    raise(e)
  File "/workspace/util.py", line 148, in host_external_check
    db.collection("external_check").document(device).set(result)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/google/cloud/firestore_v1/document.py", line 166, in set
    batch, kwargs = self._prep_set(document_data, merge, retry, timeout)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/google/cloud/firestore_v1/base_document.py", line 211, in _prep_set
    batch.set(self, document_data, merge=merge)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/google/cloud/firestore_v1/base_batch.py", line 97, in set
    write_pbs = _helpers.pbs_for_set_no_merge(
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/google/cloud/firestore_v1/_helpers.py", line 705, in pbs_for_set_no_merge
    set_pb = extractor.get_update_pb(document_path)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/google/cloud/firestore_v1/_helpers.py", line 568, in get_update_pb
    name=document_path, fields=encode_dict(self.set_fields)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/google/cloud/firestore_v1/_helpers.py", line 232, in encode_dict
    return {key: encode_value(value) for key, value in values_dict.items()}
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/google/cloud/firestore_v1/_helpers.py", line 232, in <dictcomp>
    return {key: encode_value(value) for key, value in values_dict.items()}
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/google/cloud/firestore_v1/_helpers.py", line 207, in encode_value
    value_list = tuple(encode_value(element) for element in value)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/google/cloud/firestore_v1/_helpers.py", line 207, in <genexpr>
    value_list = tuple(encode_value(element) for element in value)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/google/cloud/firestore_v1/_helpers.py", line 199, in encode_value
    document_path = getattr(value, "_document_path", None)
KeyError: '_document_path' 
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by tseaver** [comment] 2021-06-30 15:53
I cannot reproduce the reported issue:

```python
>>> doc = client.document("issue/386")
>>> nested = {"name": {"first": "John", "last": "Doe"}}
>>> doc.set(nested)
update_time {
  seconds: 1625068362
  nanos: 739235000
}

>>> doc.get().to_dict()
{'name': {'first': 'John', 'last': 'Doe'}}
```

**Comment by anantasty** [comment] 2021-07-03 19:47
Dictonary that caused the issue was this

```
{"_shodan": {"id": "976131cd-906c-48a8-b141-5f042ee4d597", "options": {"_document_path": null}, "ptr": true, "module": "rdp", "crawler": "91597136eb9b132d7cc954511e0d9cbe7ce2e377", "_document_path": null}, "hash": -1660128709, "os": null, "tags": ["self-signed"], "opts": {"raw": "030000130ed00000123400021f080002000000", "screenshot": {"bucket": "guard-dog-data", "path": "GDS_115/screenshots/20210629_16_20.jpeg", "_document_path": null}, "_document_path": null}, "timestamp": "2021-06-17T14:00:06.674644", "isp": "Cox Communications Inc.", "port": 3389, "ssl": {"chain_sha256": ["f7e0163753a2acca160d0899c149afe1c2a29c7813d62ae4205f93b6267597d0"], "jarm": "2ad2ad16d2ad2ad22c2ad2ad2ad2adfd9c9d14e4f4f67f94f0359f8b28f532", "chain": ["-----BEGIN CERTIFICATE-----\nMIIC2jCCAcKgAwIBAgIQQvOAUes0Wa1EipIobM/olzANBgkqhkiG9w0BAQsFADAW\nMRQwEgYDVQQDEwtLZWxseU9mZmljZTAeFw0yMTA2MDYwNjUzMzJaFw0yMTEyMDYw\nNjUzMzJaMBYxFDASBgNVBAMTC0tlbGx5T2ZmaWNlMIIBIjANBgkqhkiG9w0BAQEF\nAAOCAQ8AMIIBCgKCAQEA2sJNElSEyQY9/4s/UWGIyIbceZbEVjhuvYqVocFJKT5U\n5SO8RyqLlUGO6KcxwJAWSDc/rNzP7OFiK+1TdapKUqa1+6QwqLCOFgU3tEZWx2Mz\nzSd582AyWiFPPJV3YWmTfKn9/HGqpDXJLeGLWLiVH0im5mZhmZoyuoe+9nzuVOsm\nHcB38VIx8smMTcOl6Z1x5dAeg+yyxIah7L8DEO1a4iCCX6cA7lM4diAx5zzpvpn2\n56iST90LsAhCwvtj6mZsMZmzTdYgpKYnaCNYQAU715d11vcK6SNPRNyZkV/snIB0\nWR7NPwrKDNeWVwvPDCg/N7rvRNcF0PgXPU5xhiVvVQIDAQABoyQwIjATBgNVHSUE\nDDAKBggrBgEFBQcDATALBgNVHQ8EBAMCBDAwDQYJKoZIhvcNAQELBQADggEBALgM\nBPvyJ9Xv7r/UwZBMX5H9k6ZxA3pxUJvPAhdS+XGvy1XMx+RZ1gGTv5cM7tI5+E9C\nlUiG562xUKG4KQ/PLEdcC187ibuiASdrAuwCKywowK5W4v9w1OQG3xSFRepArTYg\n1zZA7XvnUkjhO5Ik3M+oCXiDpGvS8KFswQgmeWhSQzBXiUhM9TJVmSlEC80Ms0nC\nsb5f1AVSxZMppFGF/fOSSkwcyiVHSR7Lwua/+vuCiN77WJUzbmTsNoR1Vn0WrwoE\nA0fM7GJSh+qtS5IEb65Il8ZATH86YqJKJO60EcHxdXo6yCgGGYlAwJy4kE1mPEhB\n0kN7t/w0p/fpfyWDITY=\n-----END CERTIFICATE-----\n"], "dhparams": {"prime": "ffffffffffffffffadf85458a2bb4a9aafdc5620273d3cf1d8b9c583ce2d3695a9e13641146433fbcc939dce249b3ef97d2fe363630c75d8f681b202aec4617ad3df1ed5d5fd65612433f51f5f066ed0856365553ded1af3b557135e7f57c935984f0c70e0e68b77e2a689daf3efe8721df158a136ade73530acca4f483a797abc0ab182b324fb61d108a94bb2c8e3fbb96adab760d7f4681d4f42a3de394df4ae56ede76372bb190b07a7c8ee0a6d709e02fce1cdf7e2ecc03404cd28342f619172fe9ce98583ff8e4f1232eef28183c3fe3b1b4c6fad733bb5fcbc2ec22005c58ef1837d1683b2c6f34a26c1b2effa886b423861285c97ffffffffffffffff", "public_key": "1c138881a76b1c11c99dce6f10ee488c436e5f18c80b19d2a819d6b9d37e7bbddfd5e02f79cb585568e6e54ac08d024f55444485e20e46b6ea25613369e367b306bff45c96c785da8c522160cee9267102ebf28bbf82ed2671d42a93dfcccc5b0b5d48b286ad7e61714b88821ccb2682630784e9a667a83d679a4853f7f130e562b5f7b5071b411698bb4e5c913b5dd0e08264f2161d703c5fb550f2f553286c7b66cf8a55048d327f8384a64e8ed64922d523bc32a5909300c997578f2e9d030e3958f75d31a570cf7e703b8c60b55a3d0c04124d8f3bc7347cf5378128bd037e52d4ef960e7b40fbfb38704c84e3c2546a5a3986b56ed2dcd46fd5b1ec58cc", "bits": 2048, "generator": "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002", "_document_path": null}, "versions": ["TLSv1", "-SSLv2", "-SSLv3", "TLSv1.1", "TLSv1.2"], "acceptable_cas": [], "tlsext": [{"id": 65281, "name": "renegotiation_info"}], "ja3s": "364ff14b04ef93c3b4cfa429d729c0d9", "cert": {"sig_alg": "sha256WithRSAEncryption", "issued": "20210606065332Z", "expires": "20211206065332Z", "expired": false, "version": 2, "extensions": [{"data": "0\\n\\x06\\x08+\\x06\\x01\\x05\\x05\\x07\\x03\\x01", "name": "extendedKeyUsage"}, {"data": "\\x03\\x02\\x040", "name": "keyUsage"}], "fingerprint": {"sha256": "f7e0163753a2acca160d0899c149afe1c2a29c7813d62ae4205f93b6267597d0", "sha1": "53ac24920b0c1e3219795a3f9ff02bc4985a5964", "_document_path": null}, "serial": "88993378497131106732088459572999612567", "subject": {"CN": "KellyOffice", "_document_path": null}, "pubkey": {"type": "rsa", "bits": 2048, "_document_path": null}, "issuer": {"CN": "KellyOffice", "_document_path": null}, "_document_path": null}, "cipher": {"version": "TLSv1/SSLv3", "bits": 256, "name": "ECDHE-RSA-AES256-GCM-SHA384", "_document_path": null}, "trust": {"revoked": false, "browser": null, "_document_path": null}, "alpn": [], "ocsp": {"_document_path": null}, "_document_path": null}, "hostnames": ["wsip-98-190-148-36.ph.ph.cox.net"], "location": {"city": "Phoenix", "region_code": "AZ", "area_code": null, "longitude": -112.07404, "country_code3": null, "country_name": "United States", "postal_code": null, "dma_code": null, "country_code": "US", "latitude": 33.44838, "_document_path": null}, "ip": 1656656932, "domains": ["cox.net"], "org": "Cox Communications", "_id": "8660cbed-abe5-4ad4-97e0-3a6c22a11b88", "data": "Remote Desktop Protocol\n\\x03\\x00\\x00\\x13\\x0e\\xd0\\x00\\x00\\x124\\x00\\x02\\x1f\\x08\\x00\\x02\\x00\\x00\\x00", "asn": "AS22773", "transport": "tcp", "ip_str": "98.190.148.36", "screenshots": [{"bucket": "guard-dog-data", "path": "GDS_115/screenshots/20210629_16_20.jpeg", "_document_path": null}]}
```

**Comment by tseaver** [comment] 2021-07-06 15:36
@anantasty I edited your sample to remove the certificate data. However, that representation isn't a valid Python dict (`null` isn't a Python keyword).  Can you construct a reproducer which does not include private data and which *is* valid Python?

Also, what version of `google-cloud-firestore` are you using?

**Comment by craiglabenz** [comment] 2021-08-06 15:45
I've also failed to reproduce this. I converted the supplied JSON dump back into valid Python (`null` -> `None`, etc), and the latest version of `google-cloud-firestore` library successfully saved it.

Closing for now, but feel free to re-open if the error persists against the latest library version.

**Closed by craiglabenz** 2021-08-06 15:45 UTC
Labels: api: firestore, needs more info, type: question
