### ISSUE TITLE
Background thread did not exit.

### ISSUE THREAD

**Issue by 4kpt** [googleapis/python-firestore#283] opened 2020-12-23 22:15 UTC
Hi. Have the same problem.
How can i fixed it?

Python 3.7.9

attrs==20.3.0
backports-datetime-fromisoformat==1.0.0
cachetools==4.2.0
certifi==2020.12.5
chardet==3.0.4
click==7.1.2
fireo==1.3.8
google-api-core==1.23.0
google-auth==1.24.0
google-cloud-core==1.4.4
google-cloud-firestore==1.9.0
googleapis-common-protos==1.52.0
grpcio==1.34.0
idna==2.10
protobuf==3.14.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pytz==2020.4
PyYAML==5.3.1
requests==2.25.0
rsa==4.6
six==1.15.0
transitions==0.8.5
urllib3==1.26.2

**Comment by dmahugh** [comment] 2021-01-11 22:48
It's not clear what the problem is here. Can you provide steps to reproduce the issue? Thanks!

**Comment by tseaver** [comment] 2021-09-23 19:08
Closing due to lack of requested information.  Please feel free to follow-up / reopen with the requested info.

**Closed by tseaver** 2021-09-23 19:08 UTC
Labels: api: firestore, needs more info, type: bug, priority: p3
