### ISSUE TITLE
Not compatible with protobuf 3.6.1

### ISSUE THREAD

**Issue by biswajitsahu** [googleapis/python-firestore#89] opened 2020-07-09 08:43 UTC
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-firestore/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: ubuntu bionic
  - Python version: python 3.6
  - pip version: pip 20.1.1
  - `google-cloud-firestore` version: 1.8.1

#### Steps to reproduce
This happened during importing firestore package
  1. from google.cloud import firestore
 

#### Code example

```python
# example
```

#### Stack trace
```
from google.cloud import firestore
  File "/usr/local/lib/python3.6/dist-packages/google/cloud/firestore.py", line 18, in <module>
    from google.cloud.firestore_v1 import __version__
  File "/usr/local/lib/python3.6/dist-packages/google/cloud/firestore_v1/__init__.py", line 21, in <module>
    from google.cloud.firestore_v1 import types
  File "/usr/local/lib/python3.6/dist-packages/google/cloud/firestore_v1/types.py", line 29, in <module>
    from google.cloud.firestore_v1.proto import common_pb2
  File "/usr/local/lib/python3.6/dist-packages/google/cloud/firestore_v1/proto/common_pb2.py", line 24, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by HemangChothani** [comment] 2020-07-09 13:08
@biswajitsahu Yes, I am able to reproduce it, it is due to incompatible versions.

would you mind trying to install the library in a clean virtual environment?

python3 -m venv env
source env/bin/activate
python3 -m pip install google-cloud-firestore

**My environment :**
 
    google-cloud-firestore==1.8.1
    protobuf==3.12.2
    google-api-core==1.21.0
    google-cloud-core==1.3.0

**Comment by crwilcox** [comment] 2020-07-14 00:21
@biswajitsahu could you provide followup? If you run `pip freeze` did you by chance have an older version of a dependency?

**Comment by biswajitsahu** [comment] 2020-07-20 18:43
Yes, I had an older version of protobuf which came because of some other dependency. 
However, upgrading to latest version of protobuf (3.12.2) worked for me

**Comment by HemangChothani** [comment] 2020-07-21 05:26
Closing the issue as it worked for user.

**Closed by HemangChothani** 2020-07-21 05:26 UTC
Labels: api: firestore, type: question
