### ISSUE TITLE
BulkWriter did not complete all write operations

### ISSUE THREAD

**Issue by mheripsos** [googleapis/python-firestore#633] opened 2022-08-31 22:14 UTC
BulkWriter in some cases does not complete all of its write operations. 

We have filed a Google Cloud Support request, and after trying to track down the issue, they have directed us to get into contact with the developers here directly, since the issue may be related to the python library itself. 

We run a python batch job on Google Compute Engine to export the results of the main operation into Firestore. After the completion of the python script and then a few other operations, the CE Instance is torn down. 

In some non-reproducible cases, the BulkWriter class appears not to compete all of its write operations before the python process completes. The failed writes are not interspersed, but appear to occur after some point in the sequence. We have had a very hard time tracking down what has happened. There were no apparently relevant errors reported in Firestore or of the Compute Engine instance, and the problem appears to have been local to the python operation. The code is surrounded with a try-catch that dumps error logs to the file system, and it did not do so. Based on the results produced in the calling environment, we are pretty sure that the python code ran to completion without errors. 

This code previously had not used BulkWriter, but was instead making sequential write calls directly through the Firestore Client class. In those cases, we were sometimes running into document contention issues, so we have replaced the direct calls with BulkWriter calls. This has been a big improvement except for the current documented case. Some of our suspicions are that the same document-contention issues are occurring, but silently without reporting errors, or that there were some dropped packets or network issues that didn't get handled correctly. At least for now, we are stuck with writing documents with similar-ish indices, but there are no actual document contention errors in this case, and it is just a suspicion. 

We have only observed this happen in a single case (the switch to BulkWriter is pretty recent), but want to identify and correct whatever happened. The issue is not reproducible, because we have been able to re-run the same code (after clearing the partial writes) locally to completion, and it has worked correctly. Whatever happened on the CE instance did not occur again when running the code locally. 

We have run into some problems with getting good documentation on the BulkWriter class, and also suspect that there may be something we are not entirely understanding about the .flush method. It is our understanding that the flush call should prevent the python process from continuing (and returning) until after all write operations have completed. Is this not a correct understanding, and if not, how can we ensure that the python process does not terminate early? We are not entirely sure how the parallelized writes are implemented, but figure that this may be related to what occurred. 

The machine is torn down quickly after, but this can't happen before the python call returns. Is it possible that some of the writes are still pending in parallel processes after the main process has returned to the caller? This could open the possibility that the VM is torn down before all these pending writes have completed. 

I know I haven't given you a lot to go off of, but this is the best that we have. We would appreciate any recommendations on how to avoid this in the future or fix the root of the issue. 

#### Environment details

Google Cloud Engine with c2-standard-60 VM. 

  - OS type and version: Ubuntu 20.04.4 LTS
  - Python version: 3.8.10
  - pip version: 22.2.2
  - `google-cloud-firestore` version: 2.6.0

#### Steps to reproduce

Issue is stochastic and not reproducible. 

#### Code example

Here is the general flow, but not actual executing code below

```python
from google.cloud import firestore

fstore = firestore.Client()
writer = fstore.bulk_writer()
...

# create initial documents in some set y
for x in y:
  ...
  doc = fstore....document(...)
  writer.create(doc, data)
...

# merge more data into same documents in set y
for x in y:
  ...
  doc = fstore...document(...)
  writer.set(doc, data, merge = True)
...

# create sub-documents of same set of documents in set y
for x in y:
  ...
  for a in b:
    doc = fstore...document(...)...document(...)
    writer.create(doc, data)

writer.flush()
```

The calling environment:

```
...
python3 above_file.py;

# copy a bunch of files to Cloud Storage
# one of the below files will trigger a Cloud Function which tears down the machine.
gsutil -m cp -r /${RUN_ID}/output gs://${PROJECT}-storage/${RUN_ID};
```

#### Stack trace
```
There is no error. 
```

Thanks!

**Comment by craiglabenz** [comment] 2022-09-14 19:04
Sorry you've run into this issue - intermittent problems like this are the most awkward to troubleshoot, for sure.

Your understanding of the `flush` method is correct; its intended impact is as you described. Given the nested nature of this example, my initial recommendation would be to flush between each loop, thus ensuring that all parent documents are settled before attempting to write to sub-collections. This is a bit of conjecture on my end, as we're obviously lacking visibility into multiple layers of the system, but it seems likely to rule out a certain class of error that may be tricky to juggle, or which may be underreported by the server.

My second recommendation would be to introduce log statements after the `flush()` so as to determine if the GCE instance is barbarically terminating this process while its working, or if the BulkWriter errantly thinks it successfully handled each operation.

**Comment by mheripsos** [comment] 2022-09-14 20:35
Hi @craiglabenz, appreciate the response. I know it's a difficult kind of ticket to field, since it's not reproducible and we only have so much information. Regardless, we will take whatever we can get. 

At the least, we know the intended behavior of .flush, which is good to know. We will add it after each loop, and add some logging after the final flush and probably elsewhere at different points in between. 

The issue has no occurred again, but we will keep an eye out. Thanks for your help.

**Comment by falmanna** [comment] 2023-03-07 11:34
I am also facing issues regarding the `flush()` data method. Not sure if related to this.

I have a case where I need to flush the data multiple times consecutively. From my understanding, `flush()` is used if I want to continue using the `bulk_writer()` while `close()` is used to flush and stop accepting operations.

What is happening is the second flush is not getting reflected in firestore. At the moment, we don't re-init the `bulk_writer()` between flushes (similar to how we use the normal `batch()`), but it seems like it is required?
If yes, then what is the difference between `flush()` and `close()`?

**Comment by daniel-sanche** [comment] 2024-02-22 23:28
Hey falmanna, 

you should be able to call flush multiple times to flush any queued writes, while close is only used when you're done using the object. Can you share some code reproducing the issue?

**Comment by daniel-sanche** [comment] 2024-08-06 18:22
There hasn't been activity on this bug in quite a while, so since the issue hasn't been reproduced, I'm going to go ahead and close this. Feel free to re-open if it's still present though, and I can investigate some more

**Closed by daniel-sanche** 2024-08-06 18:22 UTC
Labels: api: firestore, type: bug, priority: p3
