### ISSUE TITLE
ServiceUnavailable: 503 DNS resolution failed for service: firestore.googleapis.com

### ISSUE THREAD

**Issue by eugenevk** [googleapis/python-firestore#461] opened 2021-09-29 12:45 UTC
I am trying to access the Google's Firestore in my project with Python code (in Jupyter Notebook) and for some reason the Python program never finishes. Also tried to create a document in Firestore but then I get this error:

```ServiceUnavailable: 503 DNS resolution failed for service: firestore.googleapis.com```

I created a service account in Firestore (ServiceAccount.json contains the settings). This is my code:
```
import firebase_admin

from firebase_admin import credentials
from firebase_admin import firestore

cred = credentials.Certificate('ServiceAccount.json')
firebase_admin.initialize_app(cred)
db = firestore.client()
db.collection('company').add({'name': 'Test'})
```

Only the last statement fails. This is also returned:

```_InactiveRpcError                         Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\google\api_core\grpc_helpers.py in error_remapped_callable(*args, **kwargs)
     65         try:
---> 66             return callable_(*args, **kwargs)
     67         except grpc.RpcError as exc:

C:\ProgramData\Anaconda3\lib\site-packages\grpc\_channel.py in __call__(self, request, timeout, metadata, credentials, wait_for_ready, compression)
    945                                       wait_for_ready, compression)
--> 946         return _end_unary_response_blocking(state, call, False, None)
    947 

C:\ProgramData\Anaconda3\lib\site-packages\grpc\_channel.py in _end_unary_response_blocking(state, call, with_call, deadline)
    848     else:
--> 849         raise _InactiveRpcError(state)
    850 

_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
    status = StatusCode.UNAVAILABLE
    details = "DNS resolution failed for service: firestore.googleapis.com"
    debug_error_string = "{"created":"@1632831473.221000000","description":"Resolver transient failure","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":1356,"referenced_errors":[{"created":"@1632831473.221000000","description":"DNS resolution failed for service: firestore.googleapis.com","file":"src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.cc","file_line":202,"grpc_status":14,"referenced_errors":[{"created":"@1632831473.221000000","description":"OS Error","file":"src/core/lib/iomgr/resolve_address_windows.cc","file_line":93,"os_error":"The specified class was not found.\r\n","syscall":"getaddrinfo","wsa_error":10109}]}]}"
>

The above exception was the direct cause of the following exception:

ServiceUnavailable                        Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\google\api_core\retry.py in retry_target(target, predicate, sleep_generator, deadline, on_error)
    189         try:
--> 190             return target()
    191
...
```
Please advise. I am out of ideas.

**Comment by busunkim96** [comment] 2021-09-29 14:47
Hi,

Is it possible you are sitting behind a proxy or firewall that blocks access to certain endpoints? 

Could you try this code snippet? This fetches the [discovery document for firestore](https://firestore.googleapis.com/$discovery/rest?version=v1) which is public but sits at the same endpoint "firestore.googleapis.com".

```py
import requests

response = requests.get("https://firestore.googleapis.com/\$discovery/rest?version=v1")
response.raise_for_status()

print(response.json())
```

**Comment by eugenevk** [comment] 2021-09-29 19:52
Hi Bu Sun Kim, you're spot on! When I test my code on another (personal) computer, it works all fine. Thanks!!

**Comment by eugenevk** [comment] 2021-09-30 13:44
Additional note: on my Windows computer it still isn't working. Any suggestions, because I need to migrate data from a MS Access database.

**Comment by busunkim96** [comment] 2021-09-30 23:12
Whoops I think I had a stray `\`in the URL from when I was testing with curl - could you try this instead in your Windows environment?

```py
import requests

response = requests.get("https://firestore.googleapis.com/$discovery/rest?version=v1")
response.raise_for_status()

print(response.json())
```

**Comment by eugenevk** [comment] 2021-10-01 08:30
Now your code runs fine @busunkim96. Long output. It start with this:
```
{
	'version_module': True,
	'mtlsRootUrl': 'https: //firestore.mtls.googleapis.com/',
	'icons': {
		'x32': 'http: //www.google.com/images/icons/product/search-32.gif',
		'x16': 'http: //www.google.com/images/icons/product/search-16.gif'
	},
	'documentationLink': 'https: //cloud.google.com/firestore',
	'id': 'firestore: v1',
	'auth': {
		'oauth2': {
			'scopes': {
				'https: //www.googleapis.com/auth/datastore': {
					'description': 'ViewandmanageyourGoogleCloudDatastoredata'
				},
				'https: //www.googleapis.com/auth/cloud-platform': {
					'description': 'See,
					edit,
					configure,
					anddeleteyourGoogleClouddataandseetheemailaddressforyourGoogleAccount.'
				}
			}
		}
	},
	'schemas': {
		'GoogleFirestoreAdminV1LocationMetadata': {
			'type': 'object',
			'properties': {
				
			},
			'description': 'Themetadatamessageforgoogle.cloud.location.Location.metadata.',
			'id': 'GoogleFirestoreAdminV1LocationMetadata'
		},
		'GoogleFirestoreAdminV1Database': {
			'properties': {
				'name': {
					'description': 'TheresourcenameoftheDatabase.Format: `projects/{
						project
					}/databases/{
						database
					}`',
					'type': 'string'
				},
				'etag': {
					'type': 'string',
					'description': 'Thischecksumiscomputedbytheserverbasedonthevalueofotherfields,
					andmaybesentonupdateanddeleterequeststoensuretheclienthasanup-to-datevaluebeforeproceeding.'
				},
				'concurrencyMode': {
					'type': 'string',
					'enum': ['CONCURRENCY_MODE_UNSPECIFIED',
					'OPTIMISTIC',
					'PESSIMISTIC',
					'OPTIMISTIC_WITH_ENTITY_GROUPS'],
					'enumDescriptions': ['Notused.',
					'Useoptimisticconcurrencycontrolbydefault.ThisisthesettingforCloudFirestorecustomers.',
					'Usepessimisticconcurrencycontrolbydefault.ThisisthesettingforCloudFirestorecustomers.',
					'Useoptimisticconcurrencycontrolwithentitygroupsbydefault.ThisisthesettingforCloudDatastorecustomers.'],
					'description': 'Theconcurrencycontrolmodetouseforthisdatabase.'
				},
				'type': {
					'description': 'Thetypeofthedatabase.Seehttps: //cloud.google.com/datastore/docs/firestore-or-datastoreforinformationabouthowtochoose.',
					'enumDescriptions': ['Thedefaultvalue.Thisvalueisusedifthedatabasetypeisomitted.',
					'FirestoreNativeMode',
					'FirestoreinDatastoreMode.'],
					'enum': ['DATABASE_TYPE_UNSPECIFIED',
					'FIRESTORE_NATIVE',
					'DATASTORE_MODE'],
					'type': 'string'
				},
				'locationId': {
					'description': 'Thelocationofthedatabase.Availabledatabasesarelistedathttps: //cloud.google.com/firestore/docs/locations.',
					'type': 'string'
				}
			},
			'type': 'object',
			'description': "A Cloud Firestore Database in Native Mode. Currently one database is allowed per cloud project. It is named '(default)'",
			'id': 'GoogleFirestoreAdminV1Database'
		},
		'Write': {
			...
```

**Comment by busunkim96** [comment] 2021-10-01 18:54
Since you're able to get to the endpoint through the REST API that rules out the endpoint itself being blocked.


I believe you've tried this already, but if you have not, please please try switching to `GRPC_DNS_RESOLVER=native` (per comments in https://stackoverflow.com/questions/9361854/serviceunavailable-503-dns-resolution-failed-for-service-firestore-googleapis and https://github.com/grpc/grpc/issues/1869)

If that doesn't work, please set the following environment variables, run your program, and share the log.
```
GRPC_VERBOSITY=debug
GRPC_TRACE=cares_resolver,cares_address_sorting
```

**Some additional questions:**

1. Have you used any other Google Cloud APIs successfully with Python or any other language in the Windows environment?
2. What version of `grpcio` is installed?

```py
(env) busunkim-macbookpro% python3           
Python 3.7.9 (v3.7.9:13c94747c7, Aug 15 2020, 01:31:08) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import grpc
>>> grpc.__version__
'1.41.0'
```

**Comment by eugenevk** [comment] 2021-10-02 08:14
First of all know that I really appreciate your help @busunkim96. Thanks!

I have set the GRPC settings like this, but my program still runs forever. Apols, but I don't know where I can find the log.

![image](https://user-images.githubusercontent.com/19785727/135708797-0704897f-02f7-4179-b727-8023ffca7584.png)
And to your questions:
1. I am able to access Google Firestore (and Angolia index e.g.) in my VueJS project that I design with VS Code on my Windows 10 laptop.
2. This is the grpc version:

![image](https://user-images.githubusercontent.com/19785727/135708695-1add53ae-05e3-4f02-9fa8-eaa9c7eacae8.png)

**Comment by eugenevk** [comment] 2021-10-11 15:50
I get this in the terminal:
![image](https://user-images.githubusercontent.com/19785727/136819496-500a7d74-c83c-4334-b027-e9160ebc579e.png)

**Comment by tseaver** [comment] 2021-12-01 17:43
I'm closing this issue, as I can't foresee any possible change to the `google-cloud-firestore` client library which would resolve it.  Please follow up with a report against the https://github.com/grpc/grpc repository if you can provide information for reproducing the problem.

**Closed by tseaver** 2021-12-01 17:43 UTC
Labels: api: firestore, needs more info, type: question, external
