### ISSUE TITLE
409 Too much contention on these documents. No reason for this on consulting the documented transaction constraints.

### ISSUE THREAD

**Issue by cybermaggedon** [googleapis/python-firestore#571] opened 2022-04-26 09:56 UTC
#### Environment details

  - OS type and version: Fedora release 35
  - Python version: Python 3.10.4
  - pip version: pip 21.2.3 from /usr/lib/python3.10/site-packages/pip (python 3.10)
  - `google-cloud-firestore` version: 2.4.0
  - `firebase-admin` version: 5.2.0

#### Steps to reproduce

  0. Study documentation, and check the code doesn't violate transaction contention constraints.
  1. Run the code below, which modifies 3 documents in a transaction, 2 of which are in subcollections of the first.
  2. Reports exception `409 Too much contention on these documents. Please try again.`

#### Code example

```python
#!/usr/bin/env python3

import asyncio

from firebase_admin import firestore
import firebase_admin
from firebase_admin import credentials

firebase_admin.initialize_app()

db = firestore.AsyncClient()

# Asyncio program body
async def test():

    # References to 3 documents.  2 documents are in subcollections of the
    # parent
    parent = db.collection("test").document("P")
    child1 = parent.collection("c1").document("C1")
    child2 = parent.collection("c2").document("C2")

    # Create empty documents
    await parent.set({})
    await child1.set({})
    await child2.set({})

    # A transaction
    @firestore.async_transactional
    async def trans(tx):

        # Read 3 docs
        p = (await parent.get(transaction=tx)).to_dict()
        c1 = (await child1.get(transaction=tx)).to_dict()
        c2 = (await child2.get(transaction=tx)).to_dict()

        # Write 2 child docs
        await child1.set(c1)
        await child2.set(c2)
    # END OF TRANSACTION

    # INVOKE TRANSACTION
    # Sleep, for no reason
    await asyncio.sleep(5)

    print("TX GO")

    # Open a transactiopn
    tx = db.transaction()

    # Do transaction
    await trans(tx)

# Invoke asyncio body
asyncio.run(test())
```

#### Stack trace
```
[accounts-service]$ ./test
TX GO
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/google/api_core/grpc_helpers_async.py", line 84, in __await__
    response = yield from self._call.__await__()
  File "/usr/local/lib64/python3.10/site-packages/grpc/aio/_call.py", line 290, in __await__
    raise _create_rpc_error(self._cython_call._initial_metadata,
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.ABORTED
	details = "Too much contention on these documents. Please try again."
	debug_error_string = "{"created":"@1650966444.348194470","description":"Error received from peer ipv4:216.58.212.234:443","file":"src/core/lib/surface/call.cc","file_line":903,"grpc_message":"Too much contention on these documents. Please try again.","grpc_status":10}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mark/dev/accounts-service/./test", line 52, in <module>
    asyncio.run(test())
  File "/usr/lib64/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/mark/dev/accounts-service/./test", line 49, in test
    await trans(tx)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/firestore_v1/async_transaction.py", line 311, in __call__
    result = await self._pre_commit(transaction, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/firestore_v1/async_transaction.py", line 254, in _pre_commit
    return await self.to_wrap(transaction, *args, **kwargs)
  File "/home/mark/dev/accounts-service/./test", line 37, in trans
    await child1.set(c1)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/firestore_v1/async_document.py", line 131, in set
    write_results = await batch.commit(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/firestore_v1/async_batch.py", line 58, in commit
    commit_response = await self._client._firestore_api.commit(
  File "/usr/local/lib/python3.10/site-packages/google/cloud/firestore_v1/services/firestore/async_client.py", line 901, in commit
    response = await rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "/usr/local/lib/python3.10/site-packages/google/api_core/grpc_helpers_async.py", line 87, in __await__
    raise exceptions.from_grpc_error(rpc_error) from rpc_error
google.api_core.exceptions.Aborted: 409 Too much contention on these documents. Please try again.
```

**Comment by cybermaggedon** [comment] 2022-04-26 10:15
Even more minimal example. You can't get and set the same document in a transaction?  The documentation example does exactly that.

```
#!/usr/bin/env python3

import asyncio

from firebase_admin import firestore
import firebase_admin
from firebase_admin import credentials

firebase_admin.initialize_app()

db = firestore.AsyncClient()

# Asyncio program body
async def test():

    # References to 3 documents.  2 documents are in subcollections of the
    # parent
    child1 = db.collection("test2").document("C1")

    # Create empty documents
    await child1.set({})

    # A transaction
    @firestore.async_transactional
    async def trans(tx):
        c1 = (await child1.get(transaction=tx)).to_dict()
        await child1.set(c1)

    # Open a transactiopn
    tx = db.transaction()

    # Do transaction
    await trans(tx)

# Invoke asyncio body
asyncio.run(test())
```

**Comment by cybermaggedon** [comment] 2022-04-26 13:04
Wondered if it was the asyncio mode?  Seems not.  409 error with...
```
#!/usr/bin/env python3

from firebase_admin import firestore
import firebase_admin

firebase_admin.initialize_app()

db = firestore.Client()

# program body
def test():

    # Doc ref
    child1 = db.collection("testtest").document("test2")

    # A transaction
    @firestore.transactional
    def trans(tx):
        c1 = child1.get(transaction=tx)
        child1.set({"test": "test"})

    # Open a transactiopn
    tx = db.transaction()

    # Do transaction
    trans(tx)

test()

```

**Comment by meredithslota** [comment] 2022-05-09 20:59
@cybermaggedon Thank you for filing an issue! You mentioned above that the example used in documentation doesn't work as expected ("The documentation example does exactly that."). Can you point me to where you see this? I wonder if it's a bug in the sample code or the library.

**Comment by meredithslota** [comment] 2022-05-09 20:59
For now, tagging this as a bug so it stays on our radar.

**Comment by cybermaggedon** [comment] 2022-05-10 10:27
Thanks for taking a look @meredithslota. 

The example which gets and then sets a document is the first example on the introduction to transactions page, section title is Updating data with transactions.

https://firebase.google.com/docs/firestore/manage-data/transactions#python

**Comment by Mariatta** [comment] 2023-02-13 20:13
Hi @cybermaggedon, I was able to run your code on https://github.com/googleapis/python-firestore/issues/571#issuecomment-1109772029 and it was giving the same error: "409 Too much contention on these documents." 
I noticed that there is one difference in how we update the document on our sample page and your code.
You should use the transaction object when updating the document in the transaction.

So intsead of:
```
child1.set({"test": "test"})
```
can you try doing:
```
tx.set(child1, {"test": "test"})
```

e.g:

```
@firestore.transactional
def trans(tx):
    c1 = child1.get(transaction=tx)
    tx.set(child1, {"test": "test"})
```


I'm closing this since this appears to be problem in the code usage, and not a bug in the client library itself. If there is still an issue after you updated the code as suggested, feel free to re-open.

**Closed by Mariatta** 2023-02-13 20:13 UTC
Labels: api: firestore, type: bug, priority: p2
