### ISSUE TITLE
AioRpcError: statusCode.UNAVAILABLE, GOAWAY received

### ISSUE THREAD

**Issue by kovan** [googleapis/python-firestore#638] opened 2022-09-04 08:48 UTC
#### Environment details

  - OS type and version: Debian (python:3.10.6-slim-bullseye docker image) on Google Cloud Build
```
python --version
Python 3.10.6

```
```
pip show google-cloud-firestore
Name: google-cloud-firestore
Version: 2.6.1
```

```
pip --version
pip 22.0.3
```
#### Steps to reproduce

Maybe doing too many requests to DB the in a small amount of time? no idea really.

#### Code example

No code example because it is the whole program that is suddenly faling.

#### Stack trace
```
Step #0 - "check-for-new-videos": INFO	2022-09-04 08:26:06,971:videosdb.downloader._get_with_etag (downloader.py:425): ID: fvUHx_36cOc of collection videos not modified
Step #0 - "check-for-new-videos": INFO	2022-09-04 08:26:06,975:videosdb.downloader._get_with_etag (downloader.py:425): ID: v0q7RNIVBaQ of collection videos not modified
Step #0 - "check-for-new-videos": INFO	2022-09-04 08:26:06,986:videosdb.downloader._get_with_etag (downloader.py:425): ID: COmqxq7agfE of collection videos not modified
Step #0 - "check-for-new-videos": INFO	2022-09-04 08:26:06,988:videosdb.downloader._get_with_etag (downloader.py:425): ID: FwdNSX6yoGE of collection videos not modified
Step #0 - "check-for-new-videos": INFO	2022-09-04 08:26:07,002:videosdb.downloader._get_with_etag (downloader.py:425): ID: 6HhO-Jh_F_Y of collection videos not modified
Step #0 - "check-for-new-videos": INFO	2022-09-04 08:26:07,005:videosdb.downloader._get_with_etag (downloader.py:425): ID: V3QPzcpvbGs of collection videos not modified
Step #0 - "check-for-new-videos": INFO	2022-09-04 08:26:07,033:videosdb.downloader._get_with_etag (downloader.py:425): ID: XMhHb58chTY of collection videos not modified
Step #0 - "check-for-new-videos": INFO	2022-09-04 08:26:07,056:videosdb.downloader._get_with_etag (downloader.py:425): ID: D-aJ1J9JRQw of collection videos not modified
Step #0 - "check-for-new-videos": INFO	2022-09-04 08:26:07,086:videosdb.downloader._get_with_etag (downloader.py:425): ID: UcJeQMZGWaA of collection videos not modified
Step #0 - "check-for-new-videos": INFO	2022-09-04 08:26:07,092:videosdb.downloader._get_with_etag (downloader.py:425): ID: nUbBr2lutFk of collection videos not modified
Step #0 - "check-for-new-videos": INFO	2022-09-04 08:26:07,099:videosdb.downloader._get_with_etag (downloader.py:425): ID: Ojj_6w4GacA of collection videos not modified
Step #0 - "check-for-new-videos": INFO	2022-09-04 08:26:07,157:videosdb.downloader._get_with_etag (downloader.py:425): ID: zx2nEmDD7Wg of collection videos not modified
Step #0 - "check-for-new-videos": INFO	2022-09-04 08:26:07,166:videosdb.downloader._get_with_etag (downloader.py:425): ID: rIY-E5JO8X0 of collection videos not modified
Step #0 - "check-for-new-videos": Traceback (most recent call last):
Step #0 - "check-for-new-videos":   File "/root/videosdb/downloader.py", line 143, in check_for_new_videos_async
Step #0 - "check-for-new-videos":     await self._start()
Step #0 - "check-for-new-videos":   File "/root/videosdb/downloader.py", line 166, in _start
Step #0 - "check-for-new-videos":     async with anyio.create_task_group() as processors:
Step #0 - "check-for-new-videos":   File "/root/.cache/pypoetry/virtualenvs/videosdb-lKa0R1gD-py3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
Step #0 - "check-for-new-videos":     raise exceptions[0]
Step #0 - "check-for-new-videos":   File "/root/videosdb/downloader.py", line 214, in _playlist_processor
Step #0 - "check-for-new-videos":     async with anyio.create_task_group() as nursery:
Step #0 - "check-for-new-videos":   File "/root/.cache/pypoetry/virtualenvs/videosdb-lKa0R1gD-py3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 660, in __aexit__
Step #0 - "check-for-new-videos":     raise ExceptionGroup(exceptions)
Step #0 - "check-for-new-videos": anyio._backends._asyncio.ExceptionGroup: 3 exceptions were raised in the task group:
Step #0 - "check-for-new-videos": ----------------------------
Step #0 - "check-for-new-videos": Traceback (most recent call last):
Step #0 - "check-for-new-videos":   File "/root/.cache/pypoetry/virtualenvs/videosdb-lKa0R1gD-py3.10/lib/python3.10/site-packages/google/api_core/grpc_helpers_async.py", line 81, in __await__
Step #0 - "check-for-new-videos":     response = yield from self._call.__await__()
Step #0 - "check-for-new-videos":   File "/root/.cache/pypoetry/virtualenvs/videosdb-lKa0R1gD-py3.10/lib/python3.10/site-packages/grpc/aio/_call.py", line 290, in __await__
Step #0 - "check-for-new-videos":     raise _create_rpc_error(self._cython_call._initial_metadata,
Step #0 - "check-for-new-videos": grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
Step #0 - "check-for-new-videos": 	status = StatusCode.UNAVAILABLE
Step #0 - "check-for-new-videos": 	details = "GOAWAY received"
Step #0 - "check-for-new-videos": 	debug_error_string = "UNKNOWN:Error received from peer ipv4:173.194.215.95:443 {created_time:"2022-09-04T08:26:08.643796654+00:00", grpc_status:14, grpc_message:"GOAWAY received"}"
Step #0 - "check-for-new-videos": >
Step #0 - "check-for-new-videos": 
Step #0 - "check-for-new-videos": The above exception was the direct cause of the following exception:
Step #0 - "check-for-new-videos": 
Step #0 - "check-for-new-videos": Traceback (most recent call last):
Step #0 - "check-for-new-videos":   File "/root/videosdb/downloader.py", line 324, in _process_playlist
Step #0 - "check-for-new-videos":     await self._create_playlist(playlist, items)
Step #0 - "check-for-new-videos":   File "/root/videosdb/downloader.py", line 343, in _create_playlist
Step #0 - "check-for-new-videos":     await self.db.db.collection("playlists").document(playlist["id"]).set(playlist)
Step #0 - "check-for-new-videos":   File "/root/.cache/pypoetry/virtualenvs/videosdb-lKa0R1gD-py3.10/lib/python3.10/site-packages/google/cloud/firestore_v1/async_document.py", line 131, in set
Step #0 - "check-for-new-videos":     write_results = await batch.commit(**kwargs)
Step #0 - "check-for-new-videos":   File "/root/.cache/pypoetry/virtualenvs/videosdb-lKa0R1gD-py3.10/lib/python3.10/site-packages/google/cloud/firestore_v1/async_batch.py", line 60, in commit
Step #0 - "check-for-new-videos":     commit_response = await self._client._firestore_api.commit(
Step #0 - "check-for-new-videos":   File "/root/.cache/pypoetry/virtualenvs/videosdb-lKa0R1gD-py3.10/lib/python3.10/site-packages/google/cloud/firestore_v1/services/firestore/async_client.py", line 936, in commit
Step #0 - "check-for-new-videos":     response = await rpc(
Step #0 - "check-for-new-videos":   File "/root/.cache/pypoetry/virtualenvs/videosdb-lKa0R1gD-py3.10/lib/python3.10/site-packages/google/api_core/grpc_helpers_async.py", line 84, in __await__
Step #0 - "check-for-new-videos":     raise exceptions.from_grpc_error(rpc_error) from rpc_error
Step #0 - "check-for-new-videos": google.api_core.exceptions.ServiceUnavailable: 503 GOAWAY received
Step #0 - "check-for-new-videos": ----------------------------
Step #0 - "check-for-new-videos": Traceback (most recent call last):
Step #0 - "check-for-new-videos":   File "/root/.cache/pypoetry/virtualenvs/videosdb-lKa0R1gD-py3.10/lib/python3.10/site-packages/google/api_core/grpc_helpers_async.py", line 81, in __await__
Step #0 - "check-for-new-videos":     response = yield from self._call.__await__()
Step #0 - "check-for-new-videos":   File "/root/.cache/pypoetry/virtualenvs/videosdb-lKa0R1gD-py3.10/lib/python3.10/site-packages/grpc/aio/_call.py", line 290, in __await__
Step #0 - "check-for-new-videos":     raise _create_rpc_error(self._cython_call._initial_metadata,
Step #0 - "check-for-new-videos": grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
Step #0 - "check-for-new-videos": 	status = StatusCode.UNAVAILABLE
Step #0 - "check-for-new-videos": 	details = "GOAWAY received"
Step #0 - "check-for-new-videos": 	debug_error_string = "UNKNOWN:Error received from peer ipv4:173.194.215.95:443 {grpc_message:"GOAWAY received", grpc_status:14, created_time:"2022-09-04T08:26:08.643813764+00:00"}"
Step #0 - "check-for-new-videos": >
Step #0 - "check-for-new-videos": 
```

From all that note the error:

```
AioRpcError of RPC that terminated with:
     status = StatusCode.UNAVAILABLE
     details = "GOAWAY received"
     debug_error_string = "UNKNOWN:Error received from peer ipv4:173.194.215.95:443 {grpc_message:"GOAWAY received", grpc_status:14, created_time:"2022-09-04T08:26:08.643813764+00:00"}"
```

I can give access to the code if needed.

Thank you for your time.

**Comment by Mariatta** [comment] 2022-09-30 22:16
Hi @kovan,
We're investigating the issue. Would you be able to share the project ID where this issue has occured? Additionally, has this happened recently in the last 5 days?

**Comment by kovan** [comment] 2022-09-30 22:54
> Hi @kovan, We're investigating the issue. Would you be able to share the project ID where this issue has occured? 

worpdress-27932

> Additionally, has this happened recently in the last 5 days?

No, according to the logs it only happened the 4th of september.

**Comment by Mariatta** [comment] 2022-12-01 18:12
Closing as could not reproduce. If this happen again can you please share the project ID and let us know. Thanks.

**Closed by Mariatta** 2022-12-01 18:12 UTC
Labels: api: firestore, priority: p2
